[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu.dockerfile]
file = ".cross/x86_64-unknown-linux-gnu.dockerfile"

[target.aarch64-unknown-linux-gnu.dockerfile]
file = ".cross/aarch64-unknown-linux-gnu.dockerfile"

[target.armv7-unknown-linux-gnueabihf.dockerfile]
file = ".cross/armv7-unknown-linux-gnueabihf.dockerfile"
