[package]
name = "modulr_webrtc_message"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.17"
log = "0.4.28"
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
